version: '3.3'

services:
  crawl1:
    build: ./
    image: crawl1
    container_name: crawl1
    volumes: 
      - "./data:/code/data"
  crawler:
    image: nginx:alpine
    restart: always
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./data:/usr/share/nginx/html/file
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.cr-secure.entrypoints=websecure"
      - "traefik.http.routers.cr-secure.rule=Host(`gadgets.luxcard.vn`)"
    environment:
      - PAGE=1
    networks:
      - proxy
networks:
  proxy:
    external: true